### ISSUE TITLE
Form Dup Login-Issue on phone

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/Craft-Management#62]
Problem: When opening the email confirmation to either view or duplicate submission, the form won't open, even after using the log-in here link in the email. 

Proposed Solution:
Add a "Log into Kobo" link.
We thought that logging into Enketo was the solution, but it looks like we were mistaken that logging into enketo only would work. Use instead this kobotoolbox login https://kf.kobotoolbox.org/accounts/login/?next=/#/ 

Trevor wants to test a re-direct option first...

**Comment by brianwdavis** [comment]
https://github.com/precision-sustainable-ag/craft-forms-api/pull/46

**Comment by brianwdavis** [comment]
I tested the `?next=` parameter and couldn't get anything to work, but hopefully Trevor can find a solution and do a later patch
